// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    return $('.ours').click(function() {
      return $.ajax({
        url: 'http://127.0.0.1:8071/motion-control/update',
        type: 'POST',
        data: {
          forward: 1
        },
        dataType: 'jsonp'
      });
    });
  });

}).call(this);
