// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var degree;
    degree = 0;
    return $(window).keypress(function(event) {
      var image;
      image = $('.main');
      console.log('hit');
      console.log(degree);
      if (event.keyCode === 119) {
        $.ajax({
          url: 'http://127.0.0.1:8071/motion-control/update',
          type: 'POST',
          data: {
            forward: 1
          },
          dataType: 'jsonp'
        });
        return image.animate({
          top: '-=2'
        }, 0);
      } else if (event.keyCode === 115) {
        $.ajax({
          url: 'http://127.0.0.1:8071/motion-control/update',
          type: 'POST',
          data: {
            forward: -1
          },
          dataType: 'jsonp'
        });
        return image.animate({
          top: '+=2'
        }, 0);
      } else if (event.keyCode === 101) {
        $.ajax({
          url: 'http://127.0.0.1:8071/motion-control/update',
          type: 'POST',
          data: {
            turn: 1
          },
          dataType: 'jsonp'
        });
        degree += 2;
        return image.css({
          '-webkit-transform': 'rotate(' + degree + 'deg)'
        });
      } else if (event.keyCode === 113) {
        $.ajax({
          url: 'http://127.0.0.1:8071/motion-control/update',
          type: 'POST',
          data: {
            turn: -1
          },
          dataType: 'jsonp'
        });
        degree -= 2;
        return image.css({
          '-webkit-transform': 'rotate(' + degree + 'deg)'
        });
      } else if (event.keyCode === 100) {
        $.ajax({
          url: 'http://127.0.0.1:8071/motion-control/update',
          type: 'POST',
          data: {
            strafe: 1
          },
          dataType: 'jsonp'
        });
        return image.animate({
          left: '+=2'
        }, 0);
      } else if (event.keyCode === 97) {
        $.ajax({
          url: 'http://127.0.0.1:8071/motion-control/update',
          type: 'POST',
          data: {
            strafe: -1
          },
          dataType: 'jsonp'
        });
        return image.animate({
          left: '-=2'
        }, 0);
      } else if (event.keyCode === 32) {
        return $.ajax({
          url: 'http://127.0.0.1:8071/motion-control/update',
          type: 'POST',
          data: {
            strafe: 0
          },
          dataType: 'jsonp'
        });
      }
    });
  });

}).call(this);
